server:
  port: 8081

spring:
  application:
    name: demo-server

  profiles:
    active: dev

  cloud:
    nacos:
      username: nacos
      password: nacos
      server-addr: 192.168.189.130:8848

  zipkin:
    base-url: http://192.168.189.130:9411/

management:
  endpoints:
    web:
      exposure:
        include: '*'
